# WinCV remake 的建置環境。
# Ebiten 在 Linux 需要 X11 / OpenGL / ALSA 的開發標頭才編得起來,
# 純 golang image 不夠。交叉編 Windows 用 mingw-w64。
FROM golang:1.22-bookworm

RUN apt-get update -qq && apt-get install -y -qq --no-install-recommends \
        libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev \
        libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config \
        gcc-mingw-w64-x86-64 \
        xvfb x11-utils \
    && rm -rf /var/lib/apt/lists/*

ENV GOFLAGS=-buildvcs=false
WORKDIR /src
